### ISSUE TITLE
не используй html элементы для стилизации контента

### ISSUE THREAD

**Issue by belonog** [OlhaTitova/Coursera-mod-3-Bootstrap#5]
https://github.com/OlhaTitova/Coursera-mod-3-Bootstrap/blob/21fde8d609a4f14c809c48b0b0d8cf1c789ed2ee/index.html#L35

Я и сам делал что-то подобное на старте освоения front-end - не стоит, это плохой тон.
Лучше в данном случае применить вот такой код:
```css
.nav-item {
  border-bottom: 1px solid rgba(0,0,0,.1);
}
.nav-item:last-child {
  border: none
}
```
Так контент и его структура будут "чище" и будут отделены от стилей.
